require('./allTests/Users_tests')
require('./allTests/ExpenseTypes_tests')
require('./allTests/PaymentMethods_tests')
require('./allTests/Expenses_tests')
require('./allTests/IncomeTypes_tests')
require('./allTests/Incomes_tests')