INSERT INTO budget.expenses_category_default VALUES (DEFAULT, 'Bills');
INSERT INTO budget.expenses_category_default VALUES (DEFAULT, 'Education');
INSERT INTO budget.expenses_category_default VALUES (DEFAULT, 'Entertainment');
INSERT INTO budget.expenses_category_default VALUES (DEFAULT, 'Fees & Charges');
INSERT INTO budget.expenses_category_default VALUES (DEFAULT, 'Health');
INSERT INTO budget.expenses_category_default VALUES (DEFAULT, 'Insurances');
INSERT INTO budget.expenses_category_default VALUES (DEFAULT, 'Media');
INSERT INTO budget.expenses_category_default VALUES (DEFAULT, 'Pets');
INSERT INTO budget.expenses_category_default VALUES (DEFAULT, 'Retirement');
INSERT INTO budget.expenses_category_default VALUES (DEFAULT, 'Shopping');
INSERT INTO budget.expenses_category_default VALUES (DEFAULT, 'Transport');
INSERT INTO budget.expenses_category_default VALUES (DEFAULT, 'Travel');