INSERT INTO budget.expenses_subcategory_default VALUES (DEFAULT, 'Electricity');
INSERT INTO budget.expenses_subcategory_default VALUES (DEFAULT, 'Gas');
INSERT INTO budget.expenses_subcategory_default VALUES (DEFAULT, 'Rentals');
INSERT INTO budget.expenses_subcategory_default VALUES (DEFAULT, 'Water');
INSERT INTO budget.expenses_subcategory_default VALUES (DEFAULT, 'Books');
INSERT INTO budget.expenses_subcategory_default VALUES (DEFAULT, 'Courses');
INSERT INTO budget.expenses_subcategory_default VALUES (DEFAULT, 'Private lessons');
INSERT INTO budget.expenses_subcategory_default VALUES (DEFAULT, 'Games');
INSERT INTO budget.expenses_subcategory_default VALUES (DEFAULT, 'Movies');
INSERT INTO budget.expenses_subcategory_default VALUES (DEFAULT, 'Theater');
INSERT INTO budget.expenses_subcategory_default VALUES (DEFAULT, 'Parking fee');
INSERT INTO budget.expenses_subcategory_default VALUES (DEFAULT, 'Doctors');
INSERT INTO budget.expenses_subcategory_default VALUES (DEFAULT, 'Pharmacy');
INSERT INTO budget.expenses_subcategory_default VALUES (DEFAULT, 'Life');
INSERT INTO budget.expenses_subcategory_default VALUES (DEFAULT, 'Car');
INSERT INTO budget.expenses_subcategory_default VALUES (DEFAULT, 'Home');
INSERT INTO budget.expenses_subcategory_default VALUES (DEFAULT, 'Travel');
INSERT INTO budget.expenses_subcategory_default VALUES (DEFAULT, 'Internet');
INSERT INTO budget.expenses_subcategory_default VALUES (DEFAULT, 'Phone');
INSERT INTO budget.expenses_subcategory_default VALUES (DEFAULT, 'Television');
INSERT INTO budget.expenses_subcategory_default VALUES (DEFAULT, 'Food');
INSERT INTO budget.expenses_subcategory_default VALUES (DEFAULT, 'Veterinary');
INSERT INTO budget.expenses_subcategory_default VALUES (DEFAULT, 'Pet wellness');
INSERT INTO budget.expenses_subcategory_default VALUES (DEFAULT, 'Savings');
INSERT INTO budget.expenses_subcategory_default VALUES (DEFAULT, 'Clothing');
INSERT INTO budget.expenses_subcategory_default VALUES (DEFAULT, 'Footwear');
INSERT INTO budget.expenses_subcategory_default VALUES (DEFAULT, 'Accessories');
INSERT INTO budget.expenses_subcategory_default VALUES (DEFAULT, 'Electronics');
INSERT INTO budget.expenses_subcategory_default VALUES (DEFAULT, 'Beauty');
INSERT INTO budget.expenses_subcategory_default VALUES (DEFAULT, 'Taxi');
INSERT INTO budget.expenses_subcategory_default VALUES (DEFAULT, 'Petrol');
INSERT INTO budget.expenses_subcategory_default VALUES (DEFAULT, 'Maintenance');
INSERT INTO budget.expenses_subcategory_default VALUES (DEFAULT, 'Accomodation');