INSERT INTO budget.incomes_subcategory_default VALUES (DEFAULT, 'Bonus');
INSERT INTO budget.incomes_subcategory_default VALUES (DEFAULT, 'Monthly');
INSERT INTO budget.incomes_subcategory_default VALUES (DEFAULT, 'Yearly');
INSERT INTO budget.incomes_subcategory_default VALUES (DEFAULT, 'Occassional');
INSERT INTO budget.incomes_subcategory_default VALUES (DEFAULT, 'Birthday');
INSERT INTO budget.incomes_subcategory_default VALUES (DEFAULT, 'Name day');
INSERT INTO budget.incomes_subcategory_default VALUES (DEFAULT, 'Anniversary');
INSERT INTO budget.incomes_subcategory_default VALUES (DEFAULT, 'Without occassion');
INSERT INTO budget.incomes_subcategory_default VALUES (DEFAULT, 'Regular Job');
INSERT INTO budget.incomes_subcategory_default VALUES (DEFAULT, 'Freelance Job');
INSERT INTO budget.incomes_subcategory_default VALUES (DEFAULT, 'Scholarship');
INSERT INTO budget.incomes_subcategory_default VALUES (DEFAULT, 'Benefit');
INSERT INTO budget.incomes_subcategory_default VALUES (DEFAULT, 'Selling');
INSERT INTO budget.incomes_subcategory_default VALUES (DEFAULT, 'Parents');